[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "if [ ! -f ./whatsmeow-lib/go.mod ]; then git clone --depth=1 https://github.com/EvolutionAPI/whatsmeow.git ./whatsmeow-lib; fi && go build -o /app/server ./cmd/evolution-go"

[deploy]
startCommand = "/app/server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
